name: e2e
# Runs the CI end-to-end test network on all pushes to master or release branches
# and every pull request, but only if any Go files have been changed.
on:
  workflow_dispatch:  # allow running workflow manually
  pull_request:
  push:
    branches:
      - master
      - release/**

permissions:
  contents: read

jobs:
  e2e-test:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for technote-space/get-diff-action to get git reference
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2
        with:
          go-version: '1.17'
      - uses: actions/checkout@b0e28b5ac45a892f91e7d036f8200cf5ed489415 # v3
      - uses: technote-space/get-diff-action@832a70d288f9623f9af054e9f5d8f52df7492c0a # v6.0.1
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum

      - name: Build
        working-directory: test/e2e
        # Run two make jobs in parallel, since we can't run steps in parallel.
        run: make -j2 docker runner tests
        if: "env.GIT_DIFF != ''"

      - name: Run CI testnet
        working-directory: test/e2e
        run: ./run-multiple.sh networks/ci.toml
        if: "env.GIT_DIFF != ''"
